"""empty message

Revision ID: 538f038dba71
Revises: 4c3352384bca
Create Date: 2022-07-30 22:14:59.185526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538f038dba71'
down_revision = '4c3352384bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'website_link')
    # ### end Alembic commands ###
